Portal_30/Portal/Models/ErrorViewModel.cs
using System;

namespace Portal.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Portal_30/Portal/Models/HomeViewModel.cs
using System;
using System.Data;

namespace Portal.Models
{
    public class HomeViewModel : DataTable
    {
    }
}

Portal_30/Portal/Models/LoginViewModel.cs
using System;

namespace Portal.Models
{
    public class LoginViewModel
    {
        public string Email;
        public string Password;
        public string Message;
    }
}

Portal_30/Portal/Models/PersonModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Portal.Models
{
    public class PersonModel
    {
        public string Name;
        public string Surname;
        public string Age;
        public string Birthday;
        public string IsWorking;
    }
}

Portal_30/Portal/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Portal.Models;

namespace Portal.Controllers
{
    public class AboutController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        public AboutController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

Portal_30/Portal/Controllers/BusinessController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Portal.Models;

namespace Portal.Controllers
{
    public class BusinessController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        public BusinessController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

Portal_30/Portal/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Text;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Buono.BuonoCore;
using Buono.BuonoDB;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Portal.Models;
using Portal.Classes;
using Microsoft.AspNetCore.Http;

namespace Portal.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            StringBuilder SQL = null;
            clsResponse response = new clsResponse();
            DataTable dt = null;
            DateTime stDate = clsSystemInfo.xNow;
            string session = "";

            session = HttpContext.Session.GetString("eMail");
            if (session == null)
            {
                HttpContext.Session.SetString("eMail", "aaa@bbb.com");
            }

            ViewData["SessionID"] = HttpContext.Session.GetString("eMail");

            ViewData["Title"] = "TOP@" + clsSystemInfo.xSystemID;

            clsDB db = new clsDB(clsDBInfoPool.xGetInstance().xGetDBInfo(cnstDBKind.Sys));
            db.xDBOpen();

            SQL = new StringBuilder();
            SQL.Append("select * from tbl_news ");
            SQL.Append("order by 連番 desc");
            response = db.xSelect(SQL.ToString());
            db.xDBClose();

            dt = response.xGetDataTable();

            DateTime edDate = clsSystemInfo.xNow;

            clsArgs args = new clsArgs();
            args.xAddDataTable(dt);

            ViewData["stGetDataTime"] = stDate.ToString("HH:mm:ss fff");
            ViewData["edGetDataTime"] = edDate.ToString("HH:mm:ss fff");
            
            return View(args);
        }
        public IActionResult Laboratory()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

    }
}

Portal_30/Portal/Controllers/Labo_DeepLearningController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Portal.Models;

namespace Portal.Controllers
{
    public class Labo_DeepLearningController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        public Labo_DeepLearningController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

Portal_30/Portal/Controllers/LaboratoryController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Portal.Models;

namespace Portal.Controllers
{
    public class LaboratoryController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        public LaboratoryController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

Portal_30/Portal/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Portal.Models;
using Portal.Classes;
using Microsoft.AspNetCore.Http;

namespace Portal.Controllers
{
    public class LoginController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        public LoginController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }
        public IActionResult Index()
        {
            string session = HttpContext.Session.GetString("eMail");
            if (session == null) { session = ""; }

            LoginViewModel model = new LoginViewModel();
            model.Email = session;

            return View(model);
        }

        [HttpPost]
        public ActionResult PostLogin(string pEmail, string pPassword)
        {
            HttpContext.Session.SetString("eMail", pEmail);

            LoginViewModel model = new LoginViewModel();
            model.Email = pEmail;
            model.Password = pPassword;
            model.Message = "Email='" + pEmail + "'  " + "Password='" + pPassword + "'";
            model.Message = HttpContext.Session.GetString("eMail");

            return View("Index", model);
        }
    }
}

Portal_30/Portal/Controllers/PrivacyController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Portal.Models;

namespace Portal.Controllers
{
    public class PrivacyController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        public PrivacyController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }
        public IActionResult Index()
        {
            return View();
        }
    }
}

Portal_30/Portal/Views/About/Index.cshtml
@section Header
{
    <style></style>
}

@*--------------------------------------------------------

            About.Index c-rew紹介画面

--------------------------------------------------------*@

@{
    ViewData["Title"] = "About";
}

<h1 class="display-4" style="font-size: 2.0rem;">@ViewData["Title"]</h1>

<p></p>
<div id="_div_right">
    <p>あああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああ</p>
    <p>あああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああ</p>
    <p>あああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああ</p>
    <p>あああああああああああああああああああああああああ<br />あああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああ</p>
</div>

Portal_30/Portal/Views/Business/Index.cshtml
@section Header
{
    <style></style>
}

@*--------------------------------------------------------

            Business.Index 仕事関連トップ画面

--------------------------------------------------------*@

@{
    ViewData["Title"] = "Business";
}

<h1 class="display-4" style="font-size: 2.0rem;">@ViewData["Title"]</h1>

@section Body_Right
{
    <p>あああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああ</p>
}

Portal_30/Portal/Views/Labo_DeepLearning/Index.cshtml
@section Header
{
    <style>
        #_div_left {
            max-width: 100px;
            margin-left: -15px;
            margin-right: 10px;
            border-left: solid 1px red;
            border-top: solid 1px red;
            border-right: solid 1px red;
            border-bottom: solid 1px red;
            word-wrap: break-word;
        }

        #_div_right {
            border-left: solid 1px red;
            border-top: solid 1px red;
            border-right: solid 1px red;
            border-bottom: solid 1px red;
            word-wrap: break-word;
        }
    </style>

    <style>
        #_nav-item {
            line-height: 14px;
            height: auto;
            text-decoration: none;
            margin-left: 10px;
        }

            #_nav-item:hover {
                font-weight: bold;
                background: linear-gradient(165deg, #fff, #fff 40%, #c0c0c0);
            }
    </style>
}

@*--------------------------------------------------------

    Laboratory.DeepLearning.Index ディープラーニング紹介画面

--------------------------------------------------------*@

<div>
    <p style="font-size:12px;line-height:13px;">Laboratory - <a asp-controller="Labo_DeepLearning" asp-action="Index">DeepLearning</a></p>
    <h1 style="line-height:22px;text-align:center;">Deep Learning</h1>
</div>


@section Body_Left
{
    <div id="_div_left">
        <p>
            00001111
        </p>
        <p>
            hidariaaaaaaaaaaaaaaaaaaaaaaffffffggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggaaaaaaaa
        </p>
    </div>
}

@section Body_Right
{
    <div id="_div_right">
        <p>あああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああ</p>
        <p>あああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああ</p>
        <p>あああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああ</p>
        <p>あああああああああああああああああああああああああ<br />あああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああ</p>
    </div>
}

Portal_30/Portal/Views/Laboratory/Index.cshtml
@section Header
{
    <style>
        #_div_left {
            max-width: 100px;
            margin-left: -15px;
            margin-right: 10px;
            border-left: solid 1px red;
            border-top: solid 1px red;
            border-right: solid 1px red;
            border-bottom: solid 1px red;
            word-wrap: break-word;
        }

        #_div_right {
            border-left: solid 1px red;
            border-top: solid 1px red;
            border-right: solid 1px red;
            border-bottom: solid 1px red;
            word-wrap: break-word;
        }
    </style>

    <style>
        #_nav-item {
            line-height: 14px;
            height: auto;
            text-decoration: none;
            margin-left: 10px;
        }

            #_nav-item:hover {
                font-weight: bold;
                background: linear-gradient(165deg, #fff, #fff 40%, #c0c0c0);
            }
    </style>
    <style>
        #_p_no {
            font-size: 16px;
            margin-bottom:4px;
        }

        #_p_item {
        }
    </style>

    <style>
        #_box_out {
            word-wrap: break-word;
            padding: 1em 1em;
            margin-top: 1em;
            margin-bottom: 0em;
            margin-left: auto;
            margin-right: auto;
            background: #fff;
            border: solid 1px #6091d3; /*線*/
            border-radius: 5px; /*角の丸み*/
        }
    </style>
}

@*--------------------------------------------------------

    Laboratory.Index 研究室トップ画面

--------------------------------------------------------*@

@{
    ViewData["Title"] = "Laboratory";
}
<h1 class="display-4" style="font-size: 2.0rem;">@ViewData["Title"]</h1>


<div class="container">
    <div id="_box_out">
        <div>
            <p id="_p_no">１．<a asp-controller="Labo_DeepLearning" asp-action="Index">Deep Learning</a></p>
            <p id="_p_item">あああああああああああああ<br />ああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああ</p>
        </div>
    </div>
    <div id="_box_out">
        <div>
            <p id="_p_no">２．<a asp-controller="Labo_DeepLearning" asp-action="Index">new Propulsion Power</a></p>
            <p id="_p_item">あああああああああああああ<br />ああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああ</p>
        </div>
    </div>
    <div id="_box_out">
        <div>
            <p id="_p_no">３．<a asp-controller="Labo_DeepLearning" asp-action="Index">xxxxxxxxxx</a></p>
            <p id="_p_item">あああああああああああああ<br />ああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああ</p>
            <p id="_p_item">あああああああああああああ<br />ああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああ</p>
        </div>
    </div>
</div>

Portal_30/Portal/Views/Privacy/Index.cshtml
@section Header
{
    <style>
        #_div_left {
            max-width: 100px;
            margin-left: -15px;
            margin-right: 10px;
            border-left: solid 1px red;
            border-top: solid 1px red;
            border-right: solid 1px red;
            border-bottom: solid 1px red;
            word-wrap: break-word;
        }

        #_div_right {
            width: 100%;
            margin-left: -10px;
            border-left: solid 1px red;
            border-top: solid 1px red;
            border-right: solid 1px red;
            border-bottom: solid 1px red;
            word-wrap: break-word;
        }
    </style>
}

@*--------------------------------------------------------

    Privacy 個人情報保護方針画面

--------------------------------------------------------*@

@{
    ViewData["Title"] = "個人情報保護方針";
}
<h1 class="display-4" style="font-size: 2.0rem;">@ViewData["Title"]</h1>

@section Body_Right
{
    <div id="_div_right">
        <p>あああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああ</p>
    </div>
}

Portal_30/Portal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="jp">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @RenderSection("Header", false)

    <style>
        #_title {
            width: 130px;
            font-size: 28px;
            background-color: #fff;
            text-align: left;
            margin-left: 0px;
            margin-bottom:-8px;
            line-height:18px;
        }
    </style>

    <style>
        #_nav-item {
            line-height: 14px;
            height: auto;
            text-decoration: none;
            margin-left: 10px;
        }

            #_nav-item:hover {
                font-weight: bold;
                background: linear-gradient(165deg, #fff, #fff 40%, #c0c0c0);
            }
    </style>

    <style>
        #_footer {
            line-height: 20px;
            text-align: right;
            font-size: 12px;
            font-weight: bolder;
        }
    </style>
    <style>
        #_inline-block_left {
            display: inline-block; /* インラインブロック要素にする */
            background-color: #ccc; /* 背景色指定 */
        }

        #_inline-block_center {
            display: inline-block; /* インラインブロック要素にする */
            background-color: #ccc; /* 背景色指定 */
        }
    </style>
</head>
<body style="line-height: 1.2;">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" id="_title">c-rew.com <br /><div style="font-size:8px;text-align:center;">powerd by ASP.NET Core.</div></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse" style="padding-top: 5px; ">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item" id="_nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">TOP</a>
                        </li>
                        <li class="nav-item" id="_nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Business" asp-action="Index">Business</a>
                        </li>
                        <li class="nav-item" id="_nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Laboratory" asp-action="Index">Laboratory</a>
                        </li>
                        <li class="nav-item" id="_nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Privacy" asp-action="Index">Privacy</a>
                        </li>
                        <li class="nav-item" id="_nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="About" asp-action="Index">About</a>
                        </li>
                        <li class="nav-item" id="_nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container" style="font-family: 'Hiragino Kaku Gothic ProN', 'ヒラギノ角ゴ ProN W3', Meiryo, メイリオ, Osaka, 'MS PGothic', arial, helvetica, sans-serif;font-size:12px">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
        <div class="container" style="display:flex; margin: 0;">
                @RenderSection("Body_Left", false)
                @RenderSection("Body_Right", false)
        </div>
    </div>

    <footer class="border-top footer text-muted border-bottom box-shadow">
        <div class="container" id="_footer">
            &copy; 2020 https://www.c-rew.com
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Portal_30/Portal/Views/Shared/_Layout_001.cshtml
<!DOCTYPE html>
<html lang="jp">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @RenderSection("Header", false)

    <style>
        #_title {
            width: 200px;
            font-size: 28px;
            background-color: #fff;
            text-align: left;
            margin-left: 6px;
        }
    </style>

    <style>
        #_nav-item {
            text-decoration: none;
        }

            #_nav-item:hover {
                text-decoration: underline;
                font-weight: bold;
            }
    </style>

    <style>
        #_footer {
            line-height: 20px;
            text-align: right;
            font-size: 12px;
            font-weight: bolder;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" id="_title">c-rew.com</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse" style="padding-top: 5px; ">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item" id="_nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">TOP</a>
                        </li>
                        <li class="nav-item" id="_nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Business" asp-action="Index">Business</a>
                        </li>
                        <li class="nav-item" id="_nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Laboratory" asp-action="Index">Laboratory</a>
                        </li>
                        <li class="nav-item" id="_nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item" id="_nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        <li class="nav-item" id="_nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Login">Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted border-bottom box-shadow">
        <div class="container" id="_footer">
            &copy; 2020 https://www.c-rew.com
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Portal_30/Portal/Views/Shared/_Layout_002.cshtml
<!DOCTYPE html>
<html lang="jp">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @RenderSection("Header", false)

    <style>
        #_title {
            width: 200px;
            font-size: 28px;
            background-color: #fff;
            text-align: left;
            margin-left: 6px;
        }
    </style>

    <style>
        #_nav-item {
            line-height: 14px;
            height: auto;
            text-decoration: none;
            margin-left: 10px;
        }
        #_nav-item:hover {
            font-weight: bold;
            background: linear-gradient(165deg, #fff, #fff 40%, #c0c0c0);
        }
    </style>

    <style>
        #_footer {
            line-height: 20px;
            text-align: right;
            font-size: 12px;
            font-weight: bolder;
        }
    </style>
    <style>
        #_inline-block_left {
            display: inline-block;      /* インラインブロック要素にする */
            background-color:  #ccc;    /* 背景色指定 */
        }
        #_inline-block_center {
            display: inline-block;      /* インラインブロック要素にする */
            background-color:  #ccc;    /* 背景色指定 */
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" id="_title">c-rew.com</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse" style="padding-top: 5px; ">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item" id="_nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">TOP</a>
                        </li>
                        <li class="nav-item" id="_nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Business" asp-action="Index">Business</a>
                        </li>
                        <li class="nav-item" id="_nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Laboratory" asp-action="Index">Laboratory</a>
                        </li>
                        <li class="nav-item" id="_nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item" id="_nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        <li class="nav-item" id="_nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Login">Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        @RenderSection("Main_Left", false)
        <section>
            <div id="_inline-block_left">
            </div>
        </section>
        @RenderSection("Main_Right", false)
        <section>
            <div id="_inline-block_center">
                横並びにできます
                @RenderBody()
            </div>
        </section>

        <main role="main" class="pb-3">
        </main>
    </div>

    <footer class="border-top footer text-muted border-bottom box-shadow">
        <div class="container" id="_footer">
            &copy; 2020 https://www.c-rew.com
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>